### ISSUE TITLE
failed to download the file

### ISSUE THREAD

**Issue by ippocratis** [Radiokot/photoprism-android-client#25]
**What is wrong?**
While watching videos after some assersts are downloaded and viewed the app refuses to download another one until it is restarted

**To Reproduce**
Select video type and start watching videos 

**Screenshots**
![Screenshot_20230412-151251_PhotoPrism Gallery](https://user-images.githubusercontent.com/52239579/231453634-85904697-be9a-43f5-9dee-72e4e39829ce.png)

**Device (please complete the following information):**
 - Model: [redmi note 9s]
 - Android version: [13]
 - custom rom , rooted, unlocked bootloader, sandboxed play store

**Additional context**
Captured log

```
downloadFile(): error_occurred:
url=https://xxxxxxxxxx.com/api/v1/dl/537b4b7858d8b4d8baf56fe9457129ca18d1f008?t=ytrszspk
java.net.SocketTimeoutException: timeout
 at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:677)
 at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:686)
 at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.kt:382)
 at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:276)
 at okio.RealBufferedSource.read(RealBufferedSource.kt:189)
 at okio.ForwardingSource.read(ForwardingSource.kt:29)
 at ua.com.radiokot.photoprism.util.downloader.ProgressResponseBody$wrapSource$1.read(ProgressResponseBody.kt:31)
 at okio.RealBufferedSource.readAll(RealBufferedSource.kt:284)
 at ua.com.radiokot.photoprism.util.downloader.OkHttpObservableDownloader.download$lambda$3(OkHttpObservableDownloader.kt:71)
 at ua.com.radiokot.photoprism.util.downloader.OkHttpObservableDownloader.$r8$lambda$XFzdA4SLAvEP5mT21JqX1PCDJAQ(Unknown Source:0)
 at ua.com.radiokot.photoprism.util.downloader.OkHttpObservableDownloader$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
 at io.reactivex.rxjava3.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:41)
 at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13262)
 at io.reactivex.rxjava3.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
 at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
 at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
 at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
 at java.util.concurrent.FutureTask.run(FutureTask.java:264)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
 at java.lang.Thread.run(Thread.java:1012)
```

**Comment by ippocratis** [comment]
The api URL should be https?

**Comment by Radiokot** [comment]
Strange. Looks like a regular timeout error. 
I've faced such errors with my library. My PhotoPrism instance is running on Orange Pi, when I scroll fast in the web version it runs out of resources and restarts, which causes the temporary timeout. Could it be the issue in your case too?
Anyway, I'll try to reproduce it on my end in the app.

**Comment by ippocratis** [comment]
Ok
I think there is indeed a bug
To reproduce
Tap "open in"
While "downloading" progress bar appears,  if I cancel download or hit "back" before it finishes,  "video type" needs to be reseted  before the app can download another assert

Here is another "full" log I'm not sure it contains any additional info than the previous one

[logcat_cant_download.txt](https://github.com/Radiokot/photoprism-android-client/files/11215241/logcat_cant_download.txt)

**Comment by Radiokot** [comment]
What do you mean by ""video type" needs to be reseted"?

**Comment by ippocratis** [comment]
> What do you mean by ""video type" needs to be reseted"?

Taping on search field gives you two categories . Bookmarks and type

If I have video type selected so that the feed shows only videos and that bug happens  deselecting video type will make download available again

That or simple restarting the app

**Comment by Radiokot** [comment]
Got it, will try to reproduce

**Comment by Radiokot** [comment]
Sorry, Ippo, so far I have not been able neither to reproduce the issue nor to identify the cause in the code 🤷🏻‍♂️

**Comment by ippocratis** [comment]
> Sorry, Ippo, so far I have not been able neither to reproduce the issue nor to identify the cause in the code 🤷🏻‍♂️

Well its not a big deal at all
I mean the in app video player have reduced the possibility of encountering it even more

remember the bug on my side is that  if I stop the download proccess after hitting open with of a video the app cant download another one until I restart the app or remove the video filter that  was selected

With the in app video player a rarelly have to use the "open with" option for videos


So its actually a very minor app glitch

**Comment by Radiokot** [comment]
Ippocratis, I've found the bug 🎉
It really had nothing to do with the server, what appeared as a server timeout error was in fact waiting for the connection pool to free while it was full of not closed connections.
The fix will be included in the next release.

**Comment by ippocratis** [comment]
> Ippokratis, I've found the bug 🎉
> It really had nothing to do with the server, what appeared as a server timeout error was in fact waiting for the connection pool to free while it was full of not closed connections.
> The fix will be included in the next release.

Great job
as always

**Comment by ippocratis** [comment]
1.6.0 solves this
Thanks
