### ISSUE TITLE
Crash on loading gallery

### ISSUE THREAD

**Issue by Biert85** [Radiokot/photoprism-android-client#30]
**What is wrong?**
The app crashes when loading the gallery. On first launch I could enter my server address and credentials, but the app crashed after login. Server details have been stored as I don't have to enter them again, but the app crashes directly after opening.

I see a loading screen (search box and spinner) for about 1 second before crashing.

**To Reproduce**
1. Open Photoprism Gallery
2. Login (HTTPS, server in `/photoprism` subdir, with authentication)
3. Crash

4. Re-open app
5. Crash

**Expected behavior**
Expected to see the main view with photo gallery.

**Device (please complete the following information):**
 - Model: Google Pixel 6a
 - Android version: 13

**Additional context**
I have tried version 1.5.1, 1.5.0 and 1.4.0 from f-Droid, the APK from Github and the version from Google Play Store. All show the same crash.

I see no error output from my Photoprism server.

**Logcat logs**
```
--------- beginning of crash
04-26 14:06:52.490 10377 10377 E AndroidRuntime: FATAL EXCEPTION: main
04-26 14:06:52.490 10377 10377 E AndroidRuntime: Process: ua.com.radiokot.photoprism, PID: 10377
04-26 14:06:52.490 10377 10377 E AndroidRuntime: java.lang.IllegalStateException: Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.
04-26 14:06:52.490 10377 10377 E AndroidRuntime:  ViewHolder 1:ViewHolder{8cc0c12 position=4 id=-532034660, oldPos=-1, pLpos:-1 not recyclable(1)} 
04-26 14:06:52.490 10377 10377 E AndroidRuntime:  View Holder 2:ViewHolder{ec5a5c1 position=0 id=-532034660, oldPos=-1, pLpos:-1 not recyclable(1)} androidx.recyclerview.widget.RecyclerView{28e1527 VFED..... ......ID 0,231-1080,2667 #7f0a0116 app:id/gallery_recycler_view}, adapter:com.mikepenz.fastadapter.FastAdapter@633dde0, layout:androidx.recyclerview.widget.GridLayoutManager@cefe899, context:ua.com.radiokot.photoprism.features.gallery.view.GalleryActivity@38b9ea0
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.handleMissingPreInfoForChangeError(RecyclerView.java:4442)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:4366)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4031)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.view.View.layout(View.java:23716)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6413)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:149)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2376)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.view.View.layout(View.java:23716)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6413)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.view.View.layout(View.java:23716)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6413)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.view.View.layout(View.java:23716)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6413)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.view.View.layout(View.java:23716)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6413)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.view.View.layout(View.java:23716)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6413)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at com.android.internal.policy.DecorView.onLayout(DecorView.java:799)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.view.View.layout(View.java:23716)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6413)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4097)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3438)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2350)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9194)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:899)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:832)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:942)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7884)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
04-26 14:06:52.490 10377 10377 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by Radiokot** [comment]
Hi Geert.
First, thank you so much for the detailed report for the app that haven't ever worked properly for you.
I think I have a clue regarding the crash, but still looks weird. It looks like the first and the fifth newest "photos" in your gallery has the same hash, which I haven't ever faced. How do they look in the web version? The default search query used by the app is "order:newest public:true"

**Comment by Radiokot** [comment]
Thanks for clarification. 

Recently I've been fixing some issues with pagination and changed the code related to the issue. Could you please test if this release candidate crashes too?
https://anonfiles.com/WenaBen4z1/ua_com_radiokot_photoprism_1_5_2_rc1_apk

**Comment by Biert85** [comment]
The app no longer crashes with this version :) Thank you for the quick fix!

**Comment by Radiokot** [comment]
Hah, great, hope you'll find the app useful :) 

Still, I'm not sure what caused two items with the same identifiers (used to be the hash) to appear in the collection. In this version, I've fixed a bug that caused item duplication, but the catch is that the duped items were visually identical while having different identifiers, which didn't cause crashes.

We'll see. If you'll face other bugs in the gallery, I'm here to investigate.
